// Can you convert $100 into Bitcoin? 
// Can you print (console.log) the currency descriptions and the rates, one per line? 

let bitCoin = {
    "bpi":{
       "EUR":{
          "code":"EUR",
          "description":"Euro",
          "rate":"815.8994",
          "rate_float":815.8994,
          "symbol":"&euro;"
       },
       "GBP":{
          "code":"GBP",
          "description":"British Pound Sterling",
          "rate":"677.4879",
          "rate_float":677.4879,
          "symbol":"&pound;"
       },
       "USD":{
          "code":"USD",
          "description":"United States Dollar",
          "rate":"728.4816",
          "rate_float":728.4816,
          "symbol":"&#36;"
       }
    },
    "chartName":"Bitcoin",
    "disclaimer":"This data was generated by creating random numbers and mimics the Coinbase API JSON response structure. It is NOT real data. DO NOT USE THIS TO TRADE CRYPTOCURRENCY!",
    "time":{
       "updatedISO":"2023-02-14T20:16:14.370072"
    }
 }

// Can you convert $100 into Bitcoin? 
let exchangeRateBitcoin = bitCoin.bpi.USD.rate_float
let usdDollar = 100

let usd_to_bitcoin = exchangeRateBitcoin/usdDollar

console.log(usd_to_bitcoin)
// Can you print (console.log) the currency descriptions and the rates, one per line? 



